### ISSUE TITLE
[Feature Request] Generalize `beartype.peps.resolve_pep563()` to support C-based decorator objects

### ISSUE THREAD

**Issue by PhilipVinc** [beartype/beartype#283]
```python
import collections
import math
import operator
from functools import wraps
from typing import Union

import pytest

from plum import Dispatcher, Function, NotFoundLookupError

from beartype.peps import resolve_pep563

class A:
    @classmethod
    def create(cls):
        pass

resolve_pep563(A.create)
``
leads to
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 19
     16         pass
     18 A.create.__annotations__
---> 19 resolve_pep563(A.create)

File ~/Documents/pythonenvs/plum-dev/python-3.11.4/lib/python3.11/site-packages/beartype/peps/_pep563.py:297, in resolve_pep563(func, conf, cls_stack)
    287 # Atomically (i.e., all-at-once) replace that callable's postponed
    288 # annotations with these resolved annotations for safety and efficiency.
    289 #
   (...)
    294 # justified. Everyone benefits from replacing useless postponed annotations
    295 # with useful real annotations; so, we do so.
    296 print(type(arg_name_to_hint), arg_name_to_hint)
--> 297 func.__annotations__ = arg_name_to_hint

AttributeError: 'method' object has no attribute '__annotations__'
```

Either one should check that the annotations being substituted is empty (so don
t) or try harder to set the attribute with `òbject.setattr`?

**Comment by leycec** [comment]
**Fascinating...** *yet horrifying.* Thanks so much for the rapid-action heads up, @PhilipVinc. All this time, I've been under the bad assumption that *all* callables unconditionally defined the `__annotations__` dunder attribute – even unannotated callables. This must by why assumptions are bad.

I'm disappointed (but ultimately unsurprised) I never thought to test this edge case. This is kinda bad, so I'll get this patched and released as a new **@beartype 0.16.2** patch release. Let's go!

![](https://media.tenor.com/asheDKD_ItoAAAAC/power-rangers-hands-in.gif)

**Comment by leycec** [comment]
**Ah-ha.** I *see.* This issue isn't so much about unannotated methods being passed to `resolve_pep563()` as it is **decorated callables** (e.g., class methods, static methods, property getters, setters, and deleters). Let's rename this issue accordingly.

Incidentally, how did you even find out about our public (yet sadly still undocumented) `beartype.peps.resolve_pep563()` function? Plum, right? Is this something Plum currently needs? It probably is. Let's do this for Plum. :fist_raised:

**Comment by leycec** [comment]
**f705456359532 improves stuff!** Specifically, `resolve_pep563()` now raises reasonably human-readable and hopefully helpful exceptions when passed C-based decorator objects: e.g.,

```python
>>> from beartype.peps import resolve_pep563
>>> class A:
...     @classmethod
...     def create(cls):
...         pass
>>> resolve_pep563(A.create)
Traceback (most recent call last):
  File "/home/leycec/py/beartype/beartype/peps/_pep563.py", line 298, in resolve_pep563
    func.__annotations__ = arg_name_to_hint
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'method' object has no attribute '__annotations__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/leycec/tmp/mopy.py", line 11, in <module>
    resolve_pep563(A.create)
  File "/home/leycec/py/beartype/beartype/peps/_pep563.py", line 316, in resolve_pep563
    raise BeartypePep563Exception(
beartype.roar.BeartypePep563Exception: C-based decorator object <bound method A.create of <class '__main__.A'>>
not pure-Python callable. Consider passing the pure-Python callable underlying this C-based decorator object
instead (e.g., "__main__.A.create.__func__").
```

Good enough, @beartype. Good enough. Tonight we sleep, for tomorrow we do more meaningful stuff. :weary:

**Comment by PhilipVinc** [comment]
Thanks!
The reason I raised this is because a test in plum broke with the latest version of beartype, but it worked on 0.15 .

I thought it might have just been a bug from refactoring but... I'll try to give a deeper look and understand why 0.16 broke it.

**Comment by wesselb** [comment]
@leycec, @PhilipVinc, I've not looked into much detail, but I'm wondering if it might be possible to mutate `func.__annotations__` rather then setting it again.

I.e., instead of

```python
func.__annotations__ = arg_name_to_hint
```

do

```python
for k, v in arg_name_to_hint.items():
    func.__annotations__[k] = v
```

(Perhaps func.__annotations__.clear() before. Not sure.)

That is, 

```python
class A:
    @classmethod
    def test(cls, x: int):
        pass

A.test.__annotations__ = A.test.__annotations__   # AttributeError: 'method' object has no attribute '__annotations__'

A.test.__annotations__["x"] = float  # OK
```

**Comment by leycec** [comment]
That's... actually a really clever idea, @wesselb. I shoulda thought of that – but then I shoulda done alotta things, like hygienically clean myself on a routine basis. Instead, I @beartype. This is why my wife complains every morning.

Based on @wesselb's shock discovery that C-based decorator attribute proxies like `A.test.__annotations__` can actually be mutated piecemeal one key-value pair at a time, my New-New Idea 2.0 on how to properly tackle this while still respecting efficiency is as follows:

1. First, **just try assigning** `func.__annotations__ = arg_name_to_hint` like we currently do. This is the fastest thing to do and thus the first thing we do.
2. Next, **catch `AttributeError` exceptions raised by that assignment** – like we also currently do.
3. Last, if such an exception is raised:
   1. **Call** `func.__annotations__.clear()` exactly as you suggest, @wesselb. You dah Genius Amsterdam Man.
   1. **Mutate** `func.__annotations__` **piecemeal one key-value pair at a time.** This is the slowest thing to do and thus the last thing to do. This is also better than nothing, which is what we currently do.

I'm kinda surprised `resolve_pep563()` *ever* worked for class methods, honestly. We've always just implemented this with a brute-force assignment, which we now realize is kinda dumb. Let's do this tonight for the good of Plum! For tonight, *we code.*

**Comment by leycec** [comment]
**Resolved by 5170a2b.** Thanks so much for the helpful heads-up, @PhilipVinc, and the mind-shattering fix, @wesselb.

The `beartype.peps.resolve_pep563()` now explicitly supports the most common C-based decorator objects. This means at least the `@classmethod` and `@staticmethod` decorators and possibly more (e.g., `@property`). The @beartype test suite now explicitly tests this. I'm so sorry this broke Plum, too. That should have *never* happened. I mean, I can't really fathom how this ever worked in the first place... but it did, apparently! The world is mysterious. And this is the proof.

![](https://media.tenor.com/DRgXad_JuuQAAAAC/bobitos-mimis.gif)
<sup>Hugs to all from the decaying wetlands of Ontario, Canada – home to maple syrup, poutine, curling, ice hockey, ice fishing, and anything else with "ice" in the name.</sup>

**Comment by wesselb** [comment]
@leycec Yesssss, this is fantastic to hear! Thanks for incorporating a fix so blazingly quickly. :)

Would it a patch release that includes this commit be possible? Definitely not urgent, but it would be super convenient.

**Comment by leycec** [comment]
**Absolutely.** You got it, Plum bros. @beartype 0.16.2 is due to ship tomorrow (Friday) night with both this and the thankfully unrelated test failure at #281 resolved for everybody. In the immortal words of Jake the scrappy yellow dog...

![](https://media.tenor.com/U902tn7xZ_wAAAAC/adventure-time-jake.gif)

**Comment by wesselb** [comment]
Hell yeah. :) That sounds great!
